version: '3.3'
services:
  db:
    image:          postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=score

  server:
    build:          ./
    container_name: scorsero-server
    restart:        always
#    working_dir:    /server/j2j
#    environment:
#      - LC_ALL=C.UTF-8
#      - LANG=C.UTF-8
#      - DEBUG=1
    ports:
      - "80:8080"
#    command: tail -f /dev/null
#    command: /bin/sh
    command: sh -c "./gradlew prepareDockerProperties && ./gradlew bootRun"

    depends_on:
      - db
    secrets:
      - db.properties

secrets:
  db.properties:
    file: ./db.properties