version: '3'
services:
  db:
    image:          postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=score

  server:
    build:          ./
    container_name: scorsero-server
    restart:        always
#    working_dir:    /server/j2j
#    environment:
#      - LC_ALL=C.UTF-8
#      - LANG=C.UTF-8
#      - DEBUG=1
    ports:
      - "80:8080"
#    command: tail -f /dev/null
    command: java -jar ./build/libs/scorsero-backend-core-0.0.1-SNAPSHOT.jar
#    command:        sh -c "python3 manage.py migrate && python3 manage.py loaddata initial.json && python3 manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - ./server/j2j:/server/j2j
    depends_on:
      - db

